### ISSUE TITLE
ElasticSearch 8 support

### ISSUE THREAD

**Issue by lshahar** [mkhadher/python-elasticsearch-logger#1]
After upgrade Elasticsearch lib's from 7 to 8 getting error

 File "C:\Shahar\git\serviceA\venv\lib\site-packages\pyeslogging\handlers.py", line 10, in <module>
    from elasticsearch import Elasticsearch, RequestsHttpConnection
ImportError: cannot import name 'RequestsHttpConnection' from 'elasticsearch' (C:\Shahar\git\serviceA\venv\lib\site-packages\elasticsearch\__init__.py)

**Comment by okainov** [comment]
+1 would be great to have it
